<?php

namespace AppBundle\Repository;

/**
 * EspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspaceRepository extends \Doctrine\ORM\EntityRepository
{
}
