<?php

namespace AppBundle\Repository;

/**
 * EtreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtreRepository extends \Doctrine\ORM\EntityRepository
{
}
