<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($ville)
    {
        $query=$this->createQueryBuilder('e')
                        ->where('e.ville=  :ville')
                        ->setParameter('ville', '$ville')
                        ->getQuery();
        $events = $query->getResult();

    }
}
// $repository = $this->getDoctrine()->getRepository('AppBundle:Material');
// $query = $repository->createQueryBuilder('m')
// ->where('m.available_qty > :available_qty')
// ->andWhere()
// ->setParameter('available_qty', '0')
// ->getQuery();
//
// $materials = $query->getResult();
